--<ScriptOptions statementTerminator=";"/>

ALTER TABLE HIDROMET.SHMT_SNP_VIENTO DROP CONSTRAINT FK_SNVN_SNP;

ALTER TABLE HIDROMET.SHMT_SNP_VIENTO DROP CONSTRAINT PK_SNVN;

DROP TABLE HIDROMET.SHMT_SNP_VIENTO;

CREATE TABLE HIDROMET.SHMT_SNP_VIENTO (
		SNVN_ID NUMBER(22 , 0) NOT NULL,
		SNVN_SNP_ID NUMBER(22 , 0) NOT NULL,
		SNVN_DIRECCION NUMBER(3 , 0),
		SNVN_VELMTS NUMBER(3 , 1),
		SNVN_VELKMT NUMBER(3 , 0),
		SNVN_DIRECCION_FIX NUMBER(3 , 0),
		SNVN_VELMTS_FIX NUMBER(3 , 1),
		SNVN_VELKMT_FIX NUMBER(3 , 0),
		SNVN_USUARIO NUMBER(12 , 0) NOT NULL,
		SNVN_FECHA DATE DEFAULT sysdate  NOT NULL,
		SNVN_HORA NUMBER(2 , 0),
		SNVN_INDICADOR VARCHAR2(1)
	);

ALTER TABLE HIDROMET.SHMT_SNP_VIENTO ADD CONSTRAINT PK_SNVN PRIMARY KEY (SNVN_ID);

ALTER TABLE HIDROMET.SHMT_SNP_VIENTO ADD CONSTRAINT FK_SNVN_SNP FOREIGN KEY (SNVN_SNP_ID)
	REFERENCES HIDROMET.SHMT_SINOPTICAS (SNP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

