--<ScriptOptions statementTerminator=";"/>

CREATE TABLE HIDROMET.SHMT_SNP_PA (
		SNPA_ID NUMBER(22 , 0) NOT NULL,
		SNPA_SNP_ID NUMBER(22 , 0) NOT NULL,
		SNPA_HORA NUMBER(2 , 0) NOT NULL,
		SNPA_TA NUMBER(6 , 2),
		SNPA_LD NUMBER(6 , 2),
		SNPA_PCNE NUMBER(6 , 2),
		SNPA_PRNM NUMBER(6 , 2),
		SNPA_LB NUMBER(6 , 2),
		SNPA_AA NUMBER(6 , 2),
		SNPA_TA_FIX NUMBER(6 , 2),
		SNPA_LD_FIX NUMBER(6 , 2),
		SNPA_PCNE_FIX NUMBER(6 , 2),
		SNPA_PRNM_FIX NUMBER(6 , 2),
		SNPA_LB_FIX NUMBER(6 , 2),
		SNPA_AA_FIX NUMBER(6 , 2),
		SNPA_USUARIO NUMBER(12 , 0) NOT NULL,
		SNPA_FECHA DATE DEFAULT sysdate  NOT NULL,
		SNPA_INDICADOR VARCHAR2(1)
	);

ALTER TABLE HIDROMET.SHMT_SNP_PA ADD CONSTRAINT PK_SNPA PRIMARY KEY (SNPA_ID);

ALTER TABLE HIDROMET.SHMT_SNP_PA ADD CONSTRAINT FK_SNPA_SNP FOREIGN KEY (SNPA_SNP_ID)
	REFERENCES HIDROMET.SHMT_SINOPTICAS (SNP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

