--<ScriptOptions statementTerminator=";"/>

ALTER TABLE HIDROMET.SHMT_SNP_NB DROP CONSTRAINT FK_SNNB_FNTP;

ALTER TABLE HIDROMET.SHMT_SNP_NB DROP CONSTRAINT FK_SNNB_SNP;

ALTER TABLE HIDROMET.SHMT_SNP_NB DROP CONSTRAINT PK_SNNB;

DROP TABLE HIDROMET.SHMT_SNP_NB;

CREATE TABLE HIDROMET.SHMT_SNP_NB (
		SNNB_ID NUMBER(22 , 0) NOT NULL,
		SNNB_SNP_ID NUMBER(22 , 0) NOT NULL,
		SNNB_HORA NUMBER(2 , 0) NOT NULL,
		SNNB_BAJ_TIPO VARCHAR2(1),
		SNNB_BAJ_CANT NUMBER(1 , 0),
		SNNB_BAJ_ALTU NUMBER(6 , 0),
		SNNB_MED_TIPO VARCHAR2(1),
		SNNB_MED_CANT NUMBER(1 , 0),
		SNNB_MED_ALTU NUMBER(6 , 0),
		SNNB_ALT_TIPO VARCHAR2(1),
		SNNB_ALT_CANT NUMBER(1 , 0),
		SNNB_ALT_ALTU NUMBER(6 , 0),
		SNNB_ORO_TIPO NUMBER(1 , 0),
		SNNB_ORO_DIRE NUMBER(1 , 0),
		SNNB_ORO_ANG NUMBER(2 , 0),
		SNNB_TOTAL NUMBER(1 , 0),
		SNNB_VV_MS NUMBER(5 , 2),
		SNNB_VV_KMH NUMBER(5 , 2),
		SNNB_VISIBIL NUMBER(4 , 0),
		SNNB_ESUELO NUMBER(1 , 0),
		SNNB_FENO NUMBER(2 , 0),
		SNNB_BS NUMBER(2 , 0),
		SNNB_PREC_PM NUMBER(5 , 2),
		SNNB_PREC_PG NUMBER(5 , 2),
		SNNB_BAJ_TIPO_FIX NUMBER(1 , 0),
		SNNB_BAJ_CANT_FIX NUMBER(1 , 0),
		SNNB_BAJ_ALTU_FIX NUMBER(6 , 0),
		SNNB_MED_TIPO_FIX NUMBER(1 , 0),
		SNNB_MED_CANT_FIX NUMBER(1 , 0),
		SNNB_MED_ALTU_FIX NUMBER(6 , 0),
		SNNB_ALT_TIPO_FIX NUMBER(1 , 0),
		SNNB_ALT_CANT_FIX NUMBER(1 , 0),
		SNNB_ALT_ALTU_FIX NUMBER(6 , 0),
		SNNB_ORO_TIPO_FIX NUMBER(1 , 0),
		SNNB_ORO_DIRE_FIX NUMBER(1 , 0),
		SNNB_ORO_ANG_FIX NUMBER(2 , 0),
		SNNB_TOTAL_FIX NUMBER(1 , 0),
		SNNB_VV_MS_FIX NUMBER(5 , 2),
		SNNB_VV_KMH_FIX NUMBER(5 , 2),
		SNNB_VISIBIL_FIX NUMBER(4 , 0),
		SNNB_ESUELO_FIX NUMBER(1 , 0),
		SNNB_FENO_FIX NUMBER(2 , 0),
		SNNB_BS_FIX NUMBER(2 , 0),
		SNNB_PREC_PM_FIX NUMBER(5 , 2),
		SNNB_PREC_PG_FIX NUMBER(5 , 2),
		SNNB_USUARIO NUMBER(12 , 0) NOT NULL,
		SNNB_FECHA DATE DEFAULT sysdate  NOT NULL,
		SNNB_INDICADOR VARCHAR2(1)
	);

ALTER TABLE HIDROMET.SHMT_SNP_NB ADD CONSTRAINT PK_SNNB PRIMARY KEY (SNNB_ID);

ALTER TABLE HIDROMET.SHMT_SNP_NB ADD CONSTRAINT FK_SNNB_FNTP FOREIGN KEY (SNNB_FENO)
	REFERENCES HIDROMET.SHMT_FENOMENOS_TIPOS (FNTP_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE HIDROMET.SHMT_SNP_NB ADD CONSTRAINT FK_SNNB_SNP FOREIGN KEY (SNNB_SNP_ID)
	REFERENCES HIDROMET.SHMT_SINOPTICAS (SNP_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

